In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("C:/Users/vaishnavi/Downloads/Fintech_Capstone_Project/data/raw/02_nav_history.csv")

In [4]:
print(data.shape)

(46000, 3)

In [5]:
print(data.dtypes)

amfi_code      int64
date          object
nav          float64
dtype: object

In [6]:
data.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [7]:
print(data.columns.tolist())

['amfi_code', 'date', 'nav']

In [8]:
data['date'] = pd.to_datetime(data['date'], format='mixed', dayfirst=True)

In [9]:
print(data.dtypes)

amfi_code             int64
date         datetime64[ns]
nav                 float64
dtype: object

In [10]:
data.head()

   amfi_code       date      nav
0     119551 2022-01-03  54.3856
1     119551 2022-01-04  54.3474
2     119551 2022-01-05  54.6869
3     119551 2022-01-06  55.4550
4     119551 2022-01-07  55.3692

In [11]:
data = data.sort_values(['amfi_code', 'date']).reset_index(drop=True)

In [12]:
data.head(10)

   amfi_code       date       nav
0     100016 2022-01-03  520.4608
1     100016 2022-01-04  515.0971
2     100016 2022-01-05  521.7239
3     100016 2022-01-06  515.7880
4     100016 2022-01-07  515.1639
5     100016 2022-01-10  510.7136
6     100016 2022-01-11  513.5542
7     100016 2022-01-12  512.3195
8     100016 2022-01-13  510.2445
9     100016 2022-01-14  514.3636

In [13]:
before = len(data)
data = data.drop_duplicates(subset=['amfi_code','date'])
after = len(data)

In [14]:
print(f"duplicates removed :{before - after}")

duplicates removed :0

In [15]:
print(f"Remaining rows :{after}")

Remaining rows :46000

In [16]:
data = data.set_index('date')
data = data.groupby('amfi_code')['nav'].apply(
    lambda x: x.resample('B').asfreq().ffill()
)
data = data.reset_index(level=0).reset_index()
data.columns = ['date', 'amfi_code', 'nav']

print(data.shape)
data.head()

(46000, 3)

        date  amfi_code       nav
0 2022-01-03     100016  520.4608
1 2022-01-04     100016  515.0971
2 2022-01-05     100016  521.7239
3 2022-01-06     100016  515.7880
4 2022-01-07     100016  515.1639

In [17]:
invalid = data[data['nav'] <= 0]
print(f"Invalid nav rows (<=0): {len(invalid)}")
if len(invalid) >0:
    print(invalid)
else:
    print("Valid")

Invalid nav rows (<=0): 0
Valid

In [18]:
data.to_csv("C:/Users/vaishnavi/Downloads/Fintech_Capstone_Project/data/processed/clean_nav.csv",index=False)

In [19]:
print("saved")

saved

In [20]:
print(data.shape)

(46000, 3)

In [21]:
print("Original shape:", pd.read_csv("../data/raw/02_nav_history.csv").shape)
print("Cleaned shape:", data.shape)
print("\nDate range:", data['date'].min(), "to", data['date'].max())
print("\nUnique funds:", data['amfi_code'].nunique())

Original shape: (46000, 3)
Cleaned shape: (46000, 3)

Date range: 2022-01-03 00:00:00 to 2026-05-29 00:00:00

Unique funds: 40